from settings import *

# Create Tile Map
tilemap = [
            [WALL, WALL,   WALL,   WALL,   WALL,   WALL,   WALL,   WALL,   WALL,   WALL,   WALL,   WALL,   WALL,   WALL,   WALL],
            [WALL, GROUND, GROUND, GROUND, WALL,   GROUND, WALL,   GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND,   WALL],
            [WALL, GROUND, WALL,   GROUND, WALL,   GROUND, WALL,   GROUND, WALL,   WALL,   WALL,   GROUND, WALL,   WALL,   WALL],
            [WALL, GROUND, WALL,   GROUND, WALL,   GROUND, WALL,   GROUND, WALL,   GROUND, GROUND, GROUND, GROUND, WALL,   WALL],
            [WALL, GROUND, WALL,   GROUND, GROUND, GROUND, WALL,   GROUND, WALL,   WALL,   WALL, WALL,   GROUND, GROUND, WALL],
            [WALL, GROUND, WALL,   WALL,   GROUND, WALL,   WALL,   GROUND, WALL,   GROUND, GROUND, GROUND, GROUND, WALL,   WALL],
            [WALL, GROUND, GROUND, WALL,   GROUND, WALL,   GROUND, GROUND, WALL,   WALL,   WALL,   WALL,   WALL,   WALL,   WALL],
            [WALL, WALL,   GROUND, WALL,   GROUND, WALL,   WALL,   GROUND, WALL,   GROUND, GROUND, GROUND, GROUND, GROUND, WALL],
            [WALL, WALL,   GROUND, GROUND, GROUND, GROUND, WALL,   GROUND, WALL,   GROUND, WALL,   WALL,   WALL,   GROUND, WALL],
            [WALL, WALL,   GROUND, WALL,   WALL,   GROUND, WALL,   GROUND, WALL,   GROUND, WALL,   WALL,   WALL,   GROUND, WALL],
            [WALL, WALL,   WALL,   WALL,   WALL,   GROUND, GROUND, GROUND, GROUND, GROUND, WALL,   WALL,   WALL,   GROUND, WALL],
            [WALL, WALL,   GROUND, WALL,   WALL,   WALL,   WALL,   WALL,   WALL,   GROUND, GROUND, WALL,   GROUND, GROUND, WALL],
            [WALL, GROUND, GROUND, GROUND, WALL,   WALL,   WALL,   WALL,   WALL,   WALL,   GROUND, WALL,   FINAL,  GROUND, WALL],
            [WALL, GROUND, WALL,   GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, GROUND, WALL,   GROUND, GROUND, WALL],
            [WALL, WALL,   WALL,   WALL,   WALL,   WALL,   WALL,   WALL,   WALL,   WALL,   WALL,   WALL,   WALL,   WALL,   WALL]
          ]
